FROM node:20-alpine
WORKDIR /app

# Copy standalone build (enthält server.js im Root)
COPY dist-docker/ ./

# Environment
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

EXPOSE 3000

CMD ["node", "server.js"]
